### ISSUE TITLE
List eval of null column gives incorrect output schema

### ISSUE THREAD

**Issue by dkumor** [pola-rs/polars#11188]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
df = pl.DataFrame([
    {"a": None},
],schema={'a': pl.List(pl.Int64)})
df.with_columns(
    pl.col('a').list.eval(pl.element().cast(pl.Utf8)).alias('a_str')
).schema
```
```
{'a': List(Int64), 'a_str': List(Int64)}
```

### Issue description

When doing a list eval with a column that has all null values, the output schema is not correctly computed. In the above example, the output schema should be a list of strings. This makes code that relies on each element being a string crash whenever the frame has all nulls in the column.

### Expected behavior

```python
df = pl.DataFrame([
    {"a": [1]},
],schema={'a': pl.List(pl.Int64)})
df.with_columns(
    pl.col('a').list.eval(pl.element().cast(pl.Utf8)).alias('a_str')
).schema
```
```
{'a': List(Int64), 'a_str': List(Utf8)}
```

### Installed versions

<details>

```

--------Version info---------
Polars:              0.19.3
Index type:          UInt32
Platform:            macOS-13.5.2-arm64-arm-64bit
Python:              3.10.9 (main, Dec 15 2022, 17:11:09) [Clang 14.0.0 (clang-1400.0.29.202)]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2022.11.0
gevent:              <not installed>
matplotlib:          3.6.3
numpy:               1.25.2
pandas:              2.1.0
pyarrow:             12.0.0
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            0.8.1
xlsxwriter:          <not installed>

```

</details>

**Comment by uchiiii** [comment]
I found that this error is resolved already 👍 

```python
import polars as pl

df = pl.DataFrame([
    {"a": [1]},
],schema={'a': pl.List(pl.Int64)})
df = df.with_columns(
    pl.col('a').list.eval(pl.element().cast(pl.Utf8)).alias('a_str')
)
print(df.schema)
print(df)
```
output:
```
{'a': List(Int64), 'a_str': List(Utf8)}
shape: (1, 2)
┌───────────┬───────────┐
│ a         ┆ a_str     │
│ ---       ┆ ---       │
│ list[i64] ┆ list[str] │
╞═══════════╪═══════════╡
│ [1]       ┆ ["1"]     │
└───────────┴───────────┘
```
polar version
```
--------Version info---------
Polars:              0.19.7
Index type:          UInt32
Platform:            Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python:              3.9.16 (main, May  7 2023, 19:33:09)
[Clang 16.0.3 ]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
cloudpickle:         <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              <not installed>
gevent:              <not installed>
matplotlib:          3.8.0
numpy:               1.26.1
openpyxl:            <not installed>
pandas:              <not installed>
pyarrow:             <not installed>
pydantic:            <not installed>
pyiceberg:           <not installed>
pyxlsb:              <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>
```

**Comment by dkumor** [comment]
Looks like the sample you used is from the “expected behavior”, which uses a non-null column value to demonstrate the expected schema - nulling it causes the issue. I tried the “reproducible example” and it seems that the issue is still there in latest polars.

**Comment by uchiiii** [comment]
Oops, I made a mistake. You are correct. Let me see and hopefully fix this.

**Comment by cmdlineluser** [comment]
It looks like it's hitting the check here on line 176
https://github.com/pola-rs/polars/blob/38b532211e0ffbc5a152c756b3bd0a9d93d5bf01/crates/polars-lazy/src/dsl/list.rs#L170-L178

It seems like `output_field.data_type()` needs also be returned in this case?

**Comment by dkumor** [comment]
Thank you @uchiiii!
