### ISSUE TITLE
Support gzip compression in write_csv

### ISSUE THREAD

**Issue by Wainberg** [pola-rs/polars#13227]
### Description

Sure, you could compress the CSV on the command-line after, but this is such a common use-case that it may as well be supported by Polars itself. This is implemented in pandas, tidyverse, etc.

**Comment by nviraj** [comment]
Hello,
Is there a specific design reason why this feature is not supported? I find it really surprising that writing CSVs doesn't have compression options in Polars.

As mentioned above, most other libraries do have this capability. Currently, when we need to write a gzip CSV to S3, we end up using a different library to convert and write, or we use a context manager to write it locally and transfer via boto3. 

But to be honest, after using Polars, it feels jarring to have to switch to a different library just to do this. It would be good to have this supported natively.

**Comment by coastalwhite** [comment]
> Is there a specific design reason why this feature is not supported? I find it really surprising that writing CSVs doesn't have compression options in Polars.

Not really. It just hasn't been high on our priority list. We already have the dependencies to do it. As described in #17124, it requires a bit of API design, and it will need to work on the streaming engine.

**Comment by hirohira9119** [comment]
I’ve opened #24552, but I apologize for submitting the PR before initiating a proper discussion and accept.
In the PR, ritchie46 mentioned that decompression support for stream reading should take priority, so I expect this topic won’t progress for a while. That said, I’d like to leave a record of what I’ve implemented, so I’m documenting it here in the issue.

I’ve implemented the following design:

- Options:
  - Compression formats: `gzip` and `zstd`
    - `zstd` is currently single-threaded only
  - Compression level
- Multi-frame output:
  - Required due to current implementation constraints in Rust
    - As a result, the `zlib` format is not supported
- Compression is handled within the Rust-side `CsvWriter`.
  - I believe this also enables streaming support, but are there any other aspects that need to be addressed?

​I've limited the available option to just the compression level. I made this decision after considering the possibility of supporting multiple compression formats, as I felt it was best to maintain a good balance between core functionality and avoiding unnecessary complexity in the software.

**Comment by nviraj** [comment]
Hi @ritchie46 ,
I absolutely adore and love Polars, but this is such a major painpoint. 
It’s surprising that we still don’t have this critical functionality. Especially becuase there are so many users asking for this since 2023. 

Why does decompressing in streaming take priority over non-streaming according to your comment [here](https://github.com/pola-rs/polars/pull/24552#issuecomment-3342564277)?

Is it a matter of keeping API uniform between both? 

Would it be possible to decide on the API design first, implement it using some of the work from @hirohira9119, and then roll it out for streaming?
Thanks!

**Comment by coastalwhite** [comment]
I don't think Ritchie is saying that streaming is taking priority over non-streaming.

Currently, reading compressed CSV / NDJson can only be done in a non-streaming, where the streaming engine will just decompress the whole file first and then start reading. With IO and file formats, generally, [Postel's Law] applies: "be liberal in what you accept, and conservative in what you send". If we are going to make it possible to write away compressed CSV / NDJson, to me, it is a prerequisite that we are able to ingest that data properly.

[Postel's Law]: https://en.wikipedia.org/wiki/Robustness_principle

**Comment by ggirelli** [comment]
Hi! I love `polars` but I agree with many here that being currently unable to write directly `.csv.gz` is a pain-point.

I just wanted to bring to attention that the issue that I have seen many people hitting (IRL) that goes clearly against POLS: naively using `write_csv()` to write a `foo.csv.gz` file. This results in an uncompressed file with `.gz` extension(!!) - meaning a file that the user assumes has been compressed but has actually not. Then one needs to go and rename the file (which I find more painful than having to compress the file downstream via, e.g., command line).

If there is really no plan to implement this feature any time soon, what about raising a `NotImplementedError` when trying to use `write_csv` (or similar I/O function) to write a `.gz` file? This would highlight that the feature is not available yet and avoid any issues such as the above one.

> If we are going to make it possible to write away compressed CSV / NDJson, to me, it is a prerequisite that we are able to ingest that data properly.

I do not see how the latter is a prerequisite of the former. Could you elaborate?

**Comment by quattro** [comment]
First I'd like to thank the devs for developing such a wonderful package for python.

But, yes I just got bitten by this in our lab's software after migrating from pandas. Given the ubiquity of this behavior across other datatable/dataframe implementations in R/Python, I strongly recommend the developers to consider adopting this behavior as well.

**Comment by Voultapher** [comment]
I will look into it.
