### ISSUE TITLE
Reading CSV files with variable number of columns not supported

### ISSUE THREAD

**Issue by allspatial** [pola-rs/polars#1505]
#### Are you using Python or Rust?

Python

#### Which feature gates did you use?

This can be ignored by Python users.

#### What version of polars are you using?

0.9.12

#### What operating system are you using polars on?

macOS

#### Describe your bug.

When reading a CSV file with variable number of columns, polars assumes all rows have the number of columns inferred from the first row (?) and skips parsing any subsequent columns. Providing the columns to be parsed explicitly via the _columns_ parameter results in error:

RuntimeError: Any(NotFound("Unable to get field named \"column_4\". Valid fields: [\"column_1\", \"column_2\", \"column_3\"]"))

#### What are the steps to reproduce the behavior?

Dataset (test.csv):

a,b,c
a,b,c,d,e,f
g,h,i,j,k

**Example 1 (no error but reads only 3 columns instead of 6)**

```python
import polars as pl

df = pl.read_csv("/tmp/test.csv", has_headers=False)
```

**Example (results in error)**

```python
import polars as pl

df = pl.read_csv("/tmp/test.csv", has_header=False, infer_schema_length=0,
                 columns=["column_1", "column_2", "column_3", "column_4", "column_5", "column_6"])
```

#### What is the actual behavior?

Columns beyond the ones inferred from the first data row are not parsed.

#### What is the expected behavior?

All columns are parsed but are set to NaN/None for rows that don't have data for these columns.

**Comment by pradkrish** [comment]
I am not sure I understand the issue here. I see that `CsvReader` has an argument `max_records`, which can be used to do a full table scan for inferring the number of columns. is it about importing that variable to python API?

**Comment by ritchie46** [comment]
> I am not sure I understand the issue here. I see that `CsvReader` has an argument `max_records`, which can be used to do a full table scan for inferring the number of columns. is it about importing that variable to python API?

I think I already fixed this issue.

**Comment by pradkrish** [comment]
Okay, I will be happy to get the commit that you think might have fixed the issue.

**Comment by ghuls** [comment]
I normally fixed it here: https://github.com/pola-rs/polars/commit/ee26601f880c9367565303859f4ed41aa2c42339

**Comment by jmakov** [comment]
Any updates on this? Still doesn't work using `infer_schema_length=0` or `=None`.

**Comment by Nagaprasadvr** [comment]
is this issue resolved ?  can i take this and open a pr

**Comment by deanm0000** [comment]
@Nagaprasadvr I'm not a code reviewer so I can't give a absolutely definitive answer but @stinodego marked it as accepted and if it were fixed it'd be closed so I don't see why not.

One caveat is that it needs to be a rust fix not a python fix as the maintainers don't want feature divergence between rust and python.

**Comment by Nagaprasadvr** [comment]
ty , will take this issue and open a pr

**Comment by arnowaschk** [comment]
Is this still valid, or meant to be open (is mentioned for being closed by #14012 , see there)?

**Comment by cmdlineluser** [comment]
Someone proposed `expand_ragged_lines` recently https://github.com/pola-rs/polars/issues/21441 - which I think is what is being asked for here.

DuckDB has `null_padding=true` for it - but I don't think there's a Polars equivalent yet.

```python
duckdb.sql("from read_csv('test.csv', header=false, null_padding=true)").pl()
# shape: (3, 6)
# ┌─────────┬─────────┬─────────┬─────────┬─────────┬─────────┐
# │ column0 ┆ column1 ┆ column2 ┆ column3 ┆ column4 ┆ column5 │
# │ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     │
# │ str     ┆ str     ┆ str     ┆ str     ┆ str     ┆ bool    │
# ╞═════════╪═════════╪═════════╪═════════╪═════════╪═════════╡
# │ a       ┆ b       ┆ c       ┆ null    ┆ null    ┆ null    │
# │ a       ┆ b       ┆ c       ┆ d       ┆ e       ┆ false   │
# │ g       ┆ h       ┆ i       ┆ j       ┆ k       ┆ null    │
# └─────────┴─────────┴─────────┴─────────┴─────────┴─────────┘
```

**Comment by ritchie46** [comment]
Added in #21979. If `has_header=False` the schema inference will look at the full line length to determine the schema length instead of only the first row.
