### ISSUE TITLE
Rolling_mean with weights gives wrong result when min_periods is not None

### ISSUE THREAD

**Issue by jackaixin** [pola-rs/polars#17344]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```
# no exception but gives unexpected results

out = pl.DataFrame({'a':[1,2,3,4,5]}).with_columns(
    pl.col('a').rolling_mean(3, min_periods=0, weights=[1, 2, 3]).alias('rolling_mean_3')
)

print(out)
```

```
try:
    pl.DataFrame({'a':[1,2,None,4,5]}).with_columns(
        pl.col('a').rolling_mean(3, min_periods=1, weights=[1, 2, 3]).alias('rolling_mean_3')
    )
except pl.exceptions.PanicException as e:
    print(e)
```

### Log output

```shell
weights not yet supported on array with null values
```

### Issue description

When `min_periods` is set to 0, the first few rolling windows would have length of 1, 2, ..., window_size-1. Currently, it seems that Polars is simply doing $\dfrac{s_1 w_1 + ... + s_l w_l}{w_1 + w_2 + ... w_L}$, where $l=\text{length of window}$, and $L=\text{window size}$. (See output below.)

```
shape: (5, 2)
┌─────┬────────────────┐
│ a   ┆ rolling_mean_3 │
│ --- ┆ ---            │
│ i64 ┆ f64            │
╞═════╪════════════════╡
│ 1   ┆ 0.166667       │
│ 2   ┆ 0.833333       │
│ 3   ┆ 2.333333       │
│ 4   ┆ 3.333333       │
│ 5   ┆ 4.333333       │
└─────┴────────────────┘
```

When the rolling window has only the first row, i.e. 1, it's natural to expect that the 'mean' of that rolling period is 1, not 1/6, regardless of the weights. 

When the rolling window has $l < L$, it is still to be determined how we should assign the weights to the incomplete rolling window. For example, when the rolling window contains only [1, 2], we can assign weights [1, 2], or [2, 3]. But if we view this from a signal smoothing perspective, [2, 3] might be the better choice. 

Also, it seems that when `weights` is not None, `rolling_mean` can't handle `null` values. This is already reported in https://github.com/pola-rs/polars/issues/13771, and I totally agree with @Sage0614 on his implementation. (Having something similar to how `ewm_mean` handles nulls would be great.) Hopefully that issue could be resolved together with this current issue.

### Expected behavior

```
shape: (5, 2)
┌─────┬────────────────┐
│ a   ┆ rolling_mean_3 │
│ --- ┆ ---            │
│ i64 ┆ f64            │
╞═════╪════════════════╡
│ 1   ┆ 1.0.           │
│ 2   ┆ 1.6.           │
│ 3   ┆ 2.333333       │
│ 4   ┆ 3.333333       │
│ 5   ┆ 4.333333       │
└─────┴────────────────┘
```

### Installed versions

<details>

```
--------Version info---------
Polars:               1.0.0
Index type:           UInt32
Platform:             macOS-14.5-arm64-arm-64bit
Python:               3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]

----Optional dependencies----
adbc_driver_manager:  <not installed>
cloudpickle:          <not installed>
connectorx:           <not installed>
deltalake:            <not installed>
fastexcel:            <not installed>
fsspec:               <not installed>
gevent:               <not installed>
great_tables:         <not installed>
hvplot:               <not installed>
matplotlib:           3.8.2
nest_asyncio:         1.6.0
numpy:                1.26.2
openpyxl:             <not installed>
pandas:               2.1.4
pyarrow:              15.0.0
pydantic:             <not installed>
pyiceberg:            <not installed>
sqlalchemy:           <not installed>
torch:                <not installed>
xlsx2csv:             <not installed>
xlsxwriter:           <not installed>
```

</details>

**Comment by JulianCologne** [comment]
oh yeah, this is tricky 🤔. The "problem" is only at the start of the window

another easy example:
```python
pl.DataFrame({"x": [1, 2, 3, 4]}).with_columns(
    without_weight=pl.col("x").rolling_mean(
        window_size=2,
        min_periods=0,
    ),
    with_weight_50_50=pl.col("x").rolling_mean(
        window_size=2,
        min_periods=0,
        weights=[0.5, 0.5],
    ),
    with_weight_20_80=pl.col("x").rolling_mean(
        window_size=2,
        min_periods=0,
        weights=[0.2, 0.8],
    ),
)

# shape: (4, 4)
# ┌─────┬────────────────┬───────────────────┬───────────────────┐
# │ x   ┆ without_weight ┆ with_weight_50_50 ┆ with_weight_20_80 │
# │ --- ┆ ---            ┆ ---               ┆ ---               │
# │ i64 ┆ f64            ┆ f64               ┆ f64               │
# ╞═════╪════════════════╪═══════════════════╪═══════════════════╡
# │ 1   ┆ 1.0            ┆ 0.5               ┆ 0.2               │ 🤔  window [1]
# │ 2   ┆ 1.5            ┆ 1.5               ┆ 1.8               │ ✅  window [1, 2]
# │ 3   ┆ 2.5            ┆ 2.5               ┆ 2.8               │ ✅ 
# │ 4   ┆ 3.5            ┆ 3.5               ┆ 3.8               │ ✅ 
# └─────┴────────────────┴───────────────────┴───────────────────┘
```

First window is only `[1]`
- without weights: knows that this window has only length of 1 and divides by 1 ✅ 
- with weights: multiplies by weight without considering missing weights (should always add to 100%?!) 🤔

**Comment by jackaixin** [comment]
@Julian-J-S just wondering if this issue is going to be tackled soon. Thanks!

**Comment by pniskala** [comment]
Hmm, looks like I encountered similar unexpected behaviour for `rolling_sum` when where the first N-1 elements have incorrect values when specifying `min_periods != N` and using a weight array of N weights. 

Example:
```python
import polars as pl

pl.DataFrame(
    {
        "original": [1., 0., 0.],
    }
).with_columns(
    pl.col("original").rolling_sum(
        min_periods=1,
        window_size=3,
        weights=[1, 2, 3],
    ).alias("rolling_weighted_sum"),
)

# shape: (3, 2)
# ┌──────────┬──────────────────────┐
# │ original ┆ rolling_weighted_sum │
# │ ---      ┆ ---                  │
# │ f64      ┆ f64                  │
# ╞══════════╪══════════════════════╡
# │ 1.0      ┆ 1.0                  │
# │ 0.0      ┆ 1.0                  │
# │ 0.0      ┆ 1.0                  │
# └──────────┴──────────────────────┘
```

My expected output would be actually 3, 2, 1 in this case but I get 1, 1, 1, almost as if it is doing backwards filling of nulls on the result of `min_periods=3` call.

**Comment by MarcoGorelli** [comment]
Thanks for the report, I agree that this looks quite odd

**Comment by MarcoGorelli** [comment]
@orlp I have some memory (but can't find the issue) of you saying that weights should be removed from the rolling functions completely - is that the case? Just to decide whether this should be addressed at all

**Comment by cmdlineluser** [comment]
(Think I found it with `commenter:`[^1])

https://github.com/pola-rs/polars/issues/13966#issuecomment-1908997097

> I don't know if this is worth fixing since we'll soon be removing weights anyway.



[^1]: https://github.com/pola-rs/polars/issues?q=is%3Aissue+commenter%3Aorlp+weight+remove

**Comment by Sage0614** [comment]
@MarcoGorelli as @jackaixin mensioned, I proposed a way to efficiently do general rolling statistics with weight [#13771](https://github.com/pola-rs/polars/issues/13771) I don't see a reason why rolling function can not have weight

**Comment by ancri** [comment]
> similar issue + still unresolved and would like any fix asap
> 
> ```
> import polars as pl
> 
> testdf = pl.DataFrame({"A": [1.0, 2.0, 3.0, 4.0, 5.0, 6.0]})
> 
> testdf.with_columns(
>     rolling_mean=pl.col("A").rolling_mean(window_size=3, min_samples=2, weights=[0., 1., 0.]),
> )
> 
> shape: (6, 2)
> ┌─────┬──────────────┐
> │ A   ┆ rolling_mean │
> │ --- ┆ ---          │
> │ f64 ┆ f64          │
> ╞═════╪══════════════╡
> │ 1.0 ┆ null         │
> │ 2.0 ┆ 2.0          │
> │ 3.0 ┆ 2.0          │
> │ 4.0 ┆ 3.0          │
> │ 5.0 ┆ 4.0          │
> │ 6.0 ┆ 5.0          │
> └─────┴──────────────┘
> ```
> 
> expected `rolling_mean` second row to be 1.0 if window was correctly applied. Feels like it's pushing the window forwards to compensate when `min_periods != N` in each window. Annoying I can't backfill with `None` because I get no output when using weights.
> 
> any suggestions that allow me to do a weighted mean function over two columns (time + group) would be most welcome?

I think this is part of a broad range of problems that also affect rolling sum, which is that when calculating values where we have enough periods, but not all of the window is included the calculation, the elements used are taken from the left of the window rather than from the right, i.e. `weights[:i]` rather than `weights[i:]`. This is an obvious problem.

**Comment by kdn36** [comment]
Per 1.35.1, all queries now return the expected result, with the exception of the issue where values contain Nulls.

Example:
```python
import polars as pl

out = pl.DataFrame({'a':[1,2,3,4,5]}).with_columns(
    pl.col('a').rolling_mean(3, min_periods=0, weights=[1, 2, 3]).alias('rolling_mean_3')
)

print(out)
```
now gives
```
┌─────┬────────────────┐
│ a   ┆ rolling_mean_3 │
│ --- ┆ ---            │
│ i64 ┆ f64            │
╞═════╪════════════════╡
│ 1   ┆ 1.0            │
│ 2   ┆ 1.6            │
│ 3   ┆ 2.333333       │
│ 4   ┆ 3.333333       │
│ 5   ┆ 4.333333       │
└─────┴────────────────┘
```
Similar for the other queries as reported.

Still failing:
```python
import polars as pl

out = pl.DataFrame({'a':[1,2,None,4,5]}).with_columns(
    pl.col('a').rolling_mean(3, min_periods=1, weights=[1, 2, 3]).alias('rolling_mean_3')
)
```
gives
```
pyo3_runtime.PanicException: weights not yet supported on array with null values
```

This is tracked in a separate issue (https://github.com/pola-rs/polars/issues/13771). At a minimum, it should be an error message.

Let us know if you still seeing issues on values not containing nulls.

**Comment by kdn36** [comment]
Remaining open issue tracked here: https://github.com/pola-rs/polars/issues/13771
