### ISSUE TITLE
Can't convert df to pandas

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [pola-rs/polars#2461]
#### Are you using Python or Rust?

**Python**

#### What version of polars are you using?

0.12.16

#### What operating system are you using polars on?

CentOS Linux release 8.1.1911 (Core)

#### Describe your bug.

I have a data frame where when I call `to_pandas()` on it I get the following exception:

```
  File "XXX/polars/internals/frame.py", line 879, in to_pandas
    record_batches = self._df.to_pandas()
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: InvalidArgumentError("Chunk require all its arrays to have an equal number of rows") 
```

Before diagnosing this, I want to know, is this possibly due to an error in my code, or must this be a polars bug?

**Comment by ritchie46** [comment]
Did you have any categorical data? And could you try to rechunk before calling to_pandas?

**Comment by LiterallyUniqueLogin** [comment]
It stops throwing the error if I manually call `rechunk`. I don't believe I have categorical data - does polars ever default to treating strings in CSVs as categorical?

**Comment by ritchie46** [comment]
No this is a bug. Could you come up with a small example?

**Comment by LiterallyUniqueLogin** [comment]
Another downstream symptom that's probably related is that this dataframe which can't be properly converted is the result of a left join, and the join has not properly joined all rows - only some rows have non-null right values when all should. (If I'm looking at this right).

Here's a smallish optimized plan that's producing the dataframe which produces the errors:

```
JOIN
        (UDF
UNION [UDF
MEMTABLE: ["str_col1", "float_col1", "float_col2", "int_col1"];
        project 5/5 columns     |       details: Some([col(str_col1), col(float_col1), col(float_col2), col(int_col1), col(int_col2)]);
        selection: "None"


WITH COLUMN(S) [CAST col(str_col1).str.exact() TO Int64.alias(int_col3), CAST col(str_col1).str.exact().str.len() TO Int64.alias(int_col4), CAST col(str_col1).str.exact().str.len() TO Int64.alias(int_col5), col(str_col1).str.contains().alias(bool_col1), Utf8(some_unique_text1).alias(str_col2), CAST 1i32.alias(int_col6) TO Int64, Utf8(some_shared_text).alias(str_col3)], UDF
MEMTABLE: ["str_col1", "float_col1", "float_col2", "int_col1"];
        project 5/5 columns     |       details: Some([col(str_col1), col(float_col1), col(float_col2), col(int_col1), col(int_col2)]);
        selection: "None"


WITH COLUMN(S) [CAST col(str_col1).str.exact() TO Int64.alias(int_col3), CAST col(str_col1).str.exact().str.len() TO Int64.alias(int_col4), CAST col(str_col1).str.exact().str.len() TO Int64.alias(int_col5), col(str_col1).str.contains().alias(bool_col1), Utf8(some_unique_text2).alias(str_col2), CAST 3i32.alias(int_col6) TO Int64, Utf8(some_shared_text).alias(str_col3)]])
WITH
        (UDF
UNION [SELECT 7 COLUMNS: [Utf8(some_shared_text).alias(str_col3), col(int_col6), col(int_col3), col(p_mean_platelet_volume).alias(p_val), true.alias(bool_col1), CAST null TO Int64.alias(int_col4), CAST null TO Int64.alias(int_col5)]
FROM
CSV SCAN fname1.tab; PROJECT 3/27 COLUMNS; SELECTION: None, UDF
Aggregate
        [col(p_val).min().alias(p_val)] BY [col(int_col6), col(int_col3), col(int_col4), col(int_col5)] FROM SELECT 5 COLUMNS: [col(an_int_col).alias(int_col6), col(another_int_col).alias(int_col3), CAST col(a_str_col).str.len() TO Int64.alias(int_col4), CAST col(another_str_col).str.len() TO Int64.alias(int_col5), col(a_float_col).alias(p_val)]
FROM
CSV SCAN fname2.tab; PROJECT 5/15 COLUMNS; SELECTION: None
WITH COLUMN(S) [Utf8(some_shared_text).alias(str_col3), false.alias(bool_col1)]])
ON (left: [col(str_col3), col(int_col6), col(bool_col1), col(int_col3), col(int_col4), col(int_col5)] right: [col(str_col3), col(int_col6), col(bool_col1), col(int_col3), col(int_col4), col(int_col5)])
```

**Comment by LiterallyUniqueLogin** [comment]
For comparison, here's an optimized plan which doesn't produce the error. In my code I'm concating a list that has only one df in it instead of a list that has two, which is the only change from the error producing plan above.

```
JOIN
        (UDF
UNION [UDF
MEMTABLE: ["str_col1", "float_col1", "float_col2", "int_col1"];
        project 5/5 columns     |       details: Some([col(str_col1), col(float_col1), col(float_col2), col(int_col1), col(int_col2)]);
        selection: "None"


WITH COLUMN(S) [CAST col(str_col1).str.exact() TO Int64.alias(int_col3), CAST col(str_col1).str.exact().str.len() TO Int64.alias(int_col4), CAST col(str_col1).str.exact().str.len() TO Int64.alias(int_col5), col(str_col1).str.contains().alias(bool_col1), Utf8(some_unique_text).alias(str_col2), CAST 1i32.alias(int_col6) TO Int64, Utf8(some_shared_text).alias(str_col3)]])
WITH    
        (UDF  
UNION [SELECT 7 COLUMNS: [Utf8(some_shared_text).alias(str_col3), col(int_col6), col(int_col3), col(some_float_col).alias(float_col3), true.alias(bool_col1), CAST null TO Int64.alias(int_col4), CAST null TO Int64.alias(int_col5)]
FROM
CSV SCAN fname1.tab; PROJECT 3/27 COLUMNS; SELECTION: None, UDF
Aggregate
        [col(float_col3).min().alias(float_col3)] BY [col(int_col6), col(int_col3), col(int_col4), col(int_col5)] FROM SELECT 5 COLUMNS: [col(an_int_col).alias(int_col6), col(another_int_col).alias(int_col3), CAST col(a_str_col).str.len() TO Int64.alias(int_col4), CAST col(another_str_col).str.len() TO Int64.alias(int_col5), col(a_float_col).alias(float_col3)]
FROM 
CSV SCAN fname2.tab; PROJECT 5/15 COLUMNS; SELECTION: None
WITH COLUMN(S) [Utf8(some_shared_text).alias(str_col3), false.alias(bool_col1)]])
ON (left: [col(str_col3), col(int_col6), col(bool_col1), col(int_col3), col(int_col4), col(int_col5)] right: [col(str_col3), col(int_col6), col(bool_col1), col(int_col3), col(int_col4), col(int_col5)])
```

**Comment by ritchie46** [comment]
Which line panicked?

**Comment by LiterallyUniqueLogin** [comment]
The code failed when calling `df.to_pandas()` if that's what you mean. It doesn't fail with an error otherwise, though I believe the join results are silently wrong.

**Comment by ritchie46** [comment]
If you set `RUST_BACKTRACE=1` you get  a stacktrace. Could you share that?

**Comment by ritchie46** [comment]
Is your result correct if you rechunk? If so, I have found the issue. You have created a `DataFrame` consisting of different chunk lengths, and I must rechunk that before converting to arrow.

**Comment by ritchie46** [comment]
I think it is fixed by #2464

**Comment by LiterallyUniqueLogin** [comment]
Hi @ritchie46, fell asleep before I saw your response last night. Can you push the new build to PyPI so I can confirm if this fixes the issue? I haven't gotten manual builds working in my environment.

**Comment by LiterallyUniqueLogin** [comment]
I run `RUST_BACKTRACE=full ./my_script.py` and get the following output

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArgumentError("Chunk require all its arrays   ##to have an equal number of rows")', /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow2-0.9.0/src/chunk.rs:19:31
stack backtrace:
0:     0x15534f2a5542 - <unknown>
1:     0x15534e5f088c - <unknown>
2:     0x15534f27b9c4 - <unknown>
3:     0x15534f2a6470 - <unknown>
4:     0x15534f2a71c3 - <unknown>
5:     0x15534f2a6d78 - <unknown>
6:     0x15534f2a6cf6 - <unknown>
7:     0x15534f2a6cb2 - <unknown>
8:     0x15534dbbff20 - <unknown>
9:     0x15534dbc01f2 - <unknown>
10:     0x15534eed7834 - <unknown>
11:     0x15534e032008 - <unknown>
12:     0x15534de038aa - <unknown>
13:     0x555555691463 - _PyMethodDef_RawFastCallKeywords
at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Objects/call.c:632
14:     0x555555691463 - _PyMethodDescr_FastCallKeywords
at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Objects/descrobject.c:288
15:     0x5555556919bd - call_function
at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/ceval.c:4593
16:     0x5555557003a4 - _PyEval_EvalFrameDefault
at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/ceval.c:3110
17:     0x555555643932 - PyEval_EvalFrameEx
at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/ceval.c:547:12
18:     0x555555643932 - _PyEval_EvalCodeWithName
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/ceval.c:3930:14
19:     0x55555568f700 - _PyFunction_FastCallKeywords
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Objects/call.c:433
20:     0x5555556918e8 - call_function
at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/ceval.c:4616
21:     0x55555570474a - _PyEval_EvalFrameDefault
at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/ceval.c:3093
22:     0x555555643932 - PyEval_EvalFrameEx
at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/ceval.c:547:12
23:     0x555555643932 - _PyEval_EvalCodeWithName
at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/ceval.c:3930:14
24:     0x55555568f700 - _PyFunction_FastCallKeywords
at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Objects/call.c:433
25:     0x5555556918e8 - call_function
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/ceval.c:4616
26:     0x55555570030d - _PyEval_EvalFrameDefault
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/ceval.c:3124
27:     0x55555568f564 - PyEval_EvalFrameEx
at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/ceval.c:547:12
28:     0x55555568f564 - function_code_fastcall
at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Objects/call.c:283:14
29:     0x55555568f564 - _PyFunction_FastCallKeywords
at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Objects/call.c:408
30:     0x5555556918e8 - call_function
at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/ceval.c:4616
31:     0x55555570030d - _PyEval_EvalFrameDefault
at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/ceval.c:3124
32:     0x555555643932 - PyEval_EvalFrameEx
at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/ceval.c:547:12
33:     0x555555643932 - _PyEval_EvalCodeWithName
at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/ceval.c:3930:14
34:     0x555555644b49 - PyEval_EvalCodeEx
at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/ceval.c:3959:12
35:     0x555555724c2b - PyEval_EvalCode
at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/ceval.c:524:12
36:     0x5555557913ff - run_mod
at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/pythonrun.c:1035
37:     0x55555579b9c7 - PyRun_FileExFlags
at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/pythonrun.c:988
38:     0x55555579bb9c - PyRun_SimpleFileExFlags
at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Python/pythonrun.c:429
39:     0x55555579c129 - pymain_run_file
at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Modules/main.c:456
40:     0x55555579c129 - pymain_run_filename
at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Modules/main.c:1646
41:     0x55555579c129 - pymain_run_python
at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Modules/main.c:2907
42:     0x55555579c129 - pymain_main
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Modules/main.c:3068
43:     0x55555579c27c - _Py_UnixMain
                               at /home/conda/feedstock_root/build_artifacts/python_1607545693724/work/Modules/main.c:3103
44:     0x1555543d8873 - __libc_start_main
45:     0x555555710c99 - <unknown>
Traceback (most recent call last):
File "./my_script.py", line 284, in <module>
....
print(total_df.to_pandas())
File "/home/envs/ukb/lib/python3.7/site-packages/polars/internals/frame.py", line 879, in to_pandas
record_batches = self._df.to_pandas()
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: InvalidArgumentError("Chunk require all its arrays to have an equal number of rows")
```

**Comment by ritchie46** [comment]
> Hi @ritchie46, fell asleep before I saw your response last night. Can you push the new build to PyPI so I can confirm if this fixes the issue? I haven't gotten manual builds working in my environment.

See #2467

**Comment by LiterallyUniqueLogin** [comment]
This fixed the `to_pandas` bug. The join bug still remains. I'll open a new PR.
