### ISSUE TITLE
WhenThen chain with strings feature contains produces incorrect filtering for null values

### ISSUE THREAD

**Issue by SimonSchneider** [pola-rs/polars#3038]
#### What language are you using?

Rust

#### Which feature gates did you use?

`["lazy", "is_in", "parquet", "json", "strings", "sort_multiple", "round_series"]`

#### What version of polars are you using?

`dec5b27be78579ffb847d25029b8888230bea050`

#### What operating system are you using polars on?

OSX

#### What language version are you using

`rust 1.59`

#### Describe your bug.

When using a contains filter from the `strings` feature as a predicate in a when then chain it incorrectly matches null rows.

#### What are the steps to reproduce the behavior?

```Rust
    #[test]
    fn includes_null_predicate() -> Result<()> {
        let df = df! {
            "a" => [Some("a1"), None, None],
        }?;
        let res = df
            .lazy()
            .with_column(
                when(col("a").map(
                    move |s| {
                        s.utf8()?
                            .to_lowercase()
                            .contains("not_exist")
                            .map(Into::into)
                    },
                    GetOutput::from_type(DataType::Boolean),
                ))
                .then(lit("unexpected"))
                .when(col("a").eq(lit("a1".to_string())))
                .then(lit("good hit"))
                .otherwise(Literal(LiteralValue::Null))
                .alias("b"),
            )
            .collect()?;
        dbg!(&res);
        let exp_df = df! {
            "a" => [Some("a1"), None, None],
            "b" => [Some("good hit"), None, None],
        }?;
        assert!(res.frame_equal_missing(&exp_df));
        Ok(())
    }
```

Using the contains filter as a filter produces the correct result (shown in test below):
```Rust
    #[test]
    fn includes_null_filter() -> Result<()> {
        let df = df! {
            "a" => [Some("a1"), None, None],
        }?;
        let res = df
            .lazy()
            .filter(col("a").map(
                move |s| {
                    s.utf8()?
                        .to_lowercase()
                        .contains("not_exist")
                        .map(Into::into)
                },
                GetOutput::from_type(DataType::Boolean),
            ))
            .collect()?;
        assert_eq!(res.shape(), (0, 1));
        // THIS TEST PASSES!!

        Ok(())
    }
```

#### What is the actual behavior?

```
┌──────┬────────────┐
│ a    ┆ b          │
│ ---  ┆ ---        │
│ str  ┆ str        │
╞══════╪════════════╡
│ a1   ┆ good hit   │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ null ┆ unexpected │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ null ┆ unexpected │
└──────┴────────────┘
```

#### What is the expected behavior?

The test should pass (it does on commit `b90bcfa69014bbd24098d1366c8abff406b6b195`). Might also pass on later commits but I have not tested on which exact commit this started failing.

**Comment by ritchie46** [comment]
Thanks! resolved in #3040.

**Comment by SimonSchneider** [comment]
Thank you!

**Comment by SimonSchneider** [comment]
I ran my test suite with the new commit and it seems something else is now weird. I'll get to work on a minimal test case. But it's still within the when then chain it seems.

**Comment by SimonSchneider** [comment]
It seems my larger test (which is hard to share because there is a layer between polars and my test input) is still failing on the same issue with the new commit.
I'll dig some more but in that testcase there are more columns and filters involved.

**Comment by SimonSchneider** [comment]
@ritchie46 I have a somewhat minimal case. I'm not quite sure what the difference is between this new test and the one in the OP.

```
 #[test]
    fn polars_bug_includes_null_larger() -> Result<()> {
        let df = df! {
            "a" => ["a1", "a2", "a3", "a4", "a2"],
            "b" => [Some("tree"), None, None, None, None],
        }?;
        let res = df
            .lazy()
            .with_column(
                when(col("b").map(
                    move |s| {
                        s.utf8()?
                            .to_lowercase()
                            .contains("non-existent")
                            .map(Into::into)
                    },
                    GetOutput::from_type(DataType::Boolean),
                ))
                .then(lit("weird-1"))
                .when(col("a").eq(lit("a1".to_string())))
                .then(lit("ok1"))
                .when(col("a").eq(lit("a2".to_string())))
                .then(lit("ok2"))
                .when(lit(true))
                .then(lit("ft"))
                .otherwise(Literal(LiteralValue::Null))
                .alias("c"),
            )
            .collect()?;
        dbg!(&res);
        let exp_df = df! {
            "a" => ["a1", "a2", "a3", "a4", "a2"],
            "b" => [Some("tree"), None, None, None, None],
            "c" => ["ok1", "ok2", "ft", "ft", "ok2"]
        }?;
        assert!(res.frame_equal_missing(&exp_df));
        Ok(())
    }
```
running that test fails and res is:
```
┌─────┬──────┬─────┐
│ a   ┆ b    ┆ c   │
│ --- ┆ ---  ┆ --- │
│ str ┆ str  ┆ str │
╞═════╪══════╪═════╡
│ a1  ┆ tree ┆ ok1 │
├╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌┤
│ a2  ┆ null ┆ ok2 │
├╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌┤
│ a3  ┆ null ┆ ft  │
├╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌┤
│ a4  ┆ null ┆ ft  │
├╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌┤
│ a2  ┆ null ┆ ok2 │
└─────┴──────┴─────┘
```
If you remove the first `when().then().` it passes:
```
// THIS PASSES
#[test]
    fn polars_bug_includes_null_larger() -> Result<()> {
        let df = df! {
            "a" => ["a1", "a2", "a3", "a4", "a2"],
            "b" => [Some("tree"), None, None, None, None],
        }?;
        let res = df
            .lazy()
            .with_column(
                when(col("a").eq(lit("a1".to_string())))
                .then(lit("ok1"))
                .when(col("a").eq(lit("a2".to_string())))
                .then(lit("ok2"))
                .when(lit(true))
                .then(lit("ft"))
                .otherwise(Literal(LiteralValue::Null))
                .alias("c"),
            )
            .collect()?;
        dbg!(&res);
        let exp_df = df! {
            "a" => ["a1", "a2", "a3", "a4", "a2"],
            "b" => [Some("tree"), None, None, None, None],
            "c" => ["ok1", "ok2", "ft", "ft", "ok2"]
        }?;
        assert!(res.frame_equal_missing(&exp_df));
        Ok(())
    }
```

**Comment by SimonSchneider** [comment]
let me know if you want me to create a new bug instead of adding to this one.

**Comment by ritchie46** [comment]
My bad, was a silly bug. Fixed in #3048

**Comment by SimonSchneider** [comment]
Great work as always, thank you very much!

**Comment by ritchie46** [comment]
And thanks for the good issues. :) Always nice if I can just copy paste the tests. :smile:
